### ISSUE TITLE
The Print Speed and Flows tune settings are not cleared on starting a new print

### ISSUE THREAD

**Issue by alexborro** [ErikZalm/Marlin#1268]
If you change the Speed and Flows settings of current print (LCD "Tune->Speed", "Tune->Flow", "Tune->Flow 0"), they are not cleared on starting new print. 

For example, if you change the "Flow" to 98% and Speed to 110% in the current print, these setting keep saved until machine reset, messing subsequent prints.

These settings should be reset after finishing the print.

**Comment by gregrebholz** [comment]
I agree with others on this one.  In general I don't expect anything I set to revert automatically without a gcode being sent.  I can't really see why flow and speed would be an exception to that.  Even the extruder temperature would be held if my end-gcode in the slicer didn't include M104/M140 S0, right?  End-gcode in the slicer is the intuitive place to decide, each user for themselves, if they want the head homed vs centered vs staying at last position, or the hold an "idle" temperature on some components, idle fan speeds, or to clear speed/flow.

**Comment by alexborro** [comment]
Ok,  democracy wins :-)..  Closing this issue...

**Comment by alhirzel** [comment]
I was going to weigh in, but closed during compose... =]

My expected behavior for these flow settings is that they presist across prints but not across reset. Like others have said, this parallels things like temperatures.

@alexborro do you think having an #ifdef for this behavior would satisfy your use case? It could potentially be implemented as a "reset after each SD card print" setting. It could be as simple as doing an actual reset, if that would fit your use case.

**Comment by alexborro** [comment]
@alhirzel, the Marlin code has become a mess by many #ifdefs..  These days I was studying the planner.cpp and stepper.cpp and believe me, It is way more complicated than it should be because the #ifdefs..  Quite hard to understand the code.. 

So I prefer avoiding more #ifdefs.  When I opened this issue I thought others had the same issue which is not true. I can add a gcode in the end of my files to reset this parameters, no problem. 

And thanks for your suggestion. 

Alex.
